In [31]:
import numpy as np
import pandas as pd

In [32]:
df = pd.read_csv(r"C:\Users\HOME\Downloads\IBM HR analytics\WA_Fn-UseC_-HR-Employee-Attrition (1).csv")
print(df)

      Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales
1      49        No  Travel_Frequently        279  Research & Development
2      37       Yes      Travel_Rarely       1373  Research & Development
3      33        No  Travel_Frequently       1392  Research & Development
4      27        No      Travel_Rarely        591  Research & Development
...   ...       ...                ...        ...                     ...
1465   36        No  Travel_Frequently        884  Research & Development
1466   39        No      Travel_Rarely        613  Research & Development
1467   27        No      Travel_Rarely        155  Research & Development
1468   49        No  Travel_Frequently       1023                   Sales
1469   34        No      Travel_Rarely        628  Research & Development

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1
1                    8          1  Life Sciences              1
2                    2          2          Other              1
3                    3          4  Life Sciences              1
4                    2          1        Medical              1
...                ...        ...            ...            ...
1465                23          2        Medical              1
1466                 6          1        Medical              1
1467                 4          3  Life Sciences              1
1468                 2          3        Medical              1
1469                 8          3        Medical              1

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80
1                  2  ...                         4            80
2                  4  ...                         2            80
3                  5  ...                         3            80
4                  7  ...                         4            80
...              ...  ...                       ...           ...
1465            2061  ...                         3            80
1466            2062  ...                         1            80
1467            2064  ...                         2            80
1468            2065  ...                         4            80
1469            2068  ...                         1            80

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0
1                    1                 10                      3
2                    0                  7                      3
3                    0                  8                      3
4                    1                  6                      3
...                ...                ...                    ...
1465                 1                 17                      3
1466                 1                  9                      5
1467                 1                  6                      0
1468                 0                 17                      3
1469                 0                  6                      3

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4
1                  3              10                  7
2                  3               0                  0
3                  3               8                  7
4                  3               2                  2
...              ...             ...                ...
1465               3               5                  2
1466               3               7                  7
1467               3               6                  2
1468               2               9                  6
1469               4               4                  3

      YearsSinceLastPromotion  YearsWithCurrManager
0                           0                     5
1                           1                     7
2                           0                     0
3                           3                     0
4                           2                     2
...                       ...                   ...
1465                        0                     3
1466                        1                     7
1467                        0                     3
1468                        0                     8
1469                        1                     2

[1470 rows x 35 columns]

In [33]:
INPUT_FILE = "WA_Fn-UseC_-HR-Employee-Attrition (1).csv"
OUTPUT_FILE = "employee_attrition_cleaned.csv"

In [34]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [36]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [37]:
df.duplicated().sum()

0

In [38]:
print("Initial shape:", df.shape)

Initial shape: (1470, 35)

In [39]:
print("\nData types:\n", df.dtypes)

Data types:
 Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [40]:
print("\nNull counts:\n", df.isnull().sum()[df.isnull().sum() > 0])

Null counts:
 Series([], dtype: int64)

In [41]:
[df.isnull().sum() > 0]

[Age                         False
 Attrition                   False
 BusinessTravel              False
 DailyRate                   False
 Department                  False
 DistanceFromHome            False
 Education                   False
 EducationField              False
 EmployeeCount               False
 EmployeeNumber              False
 EnvironmentSatisfaction     False
 Gender                      False
 HourlyRate                  False
 JobInvolvement              False
 JobLevel                    False
 JobRole                     False
 JobSatisfaction             False
 MaritalStatus               False
 MonthlyIncome               False
 MonthlyRate                 False
 NumCompaniesWorked          False
 Over18                      False
 OverTime                    False
 PercentSalaryHike           False
 PerformanceRating           False
 RelationshipSatisfaction    False
 StandardHours               False
 StockOptionLevel            False
 TotalWorkingYears           False
 TrainingTimesLastYear       False
 WorkLifeBalance             False
 YearsAtCompany              False
 YearsInCurrentRole          False
 YearsSinceLastPromotion     False
 YearsWithCurrManager        False
 dtype: bool]

In [42]:
print("\nDuplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [44]:
df.drop_duplicates(inplace=True)

In [45]:
df["Attrition_Flag"] = df["Attrition"].map({
    "Yes":1,
    "No":0
})

In [46]:
df["OverTime_Flag"] = df["OverTime"].map({
    "Yes":1,
    "No":0
})

In [47]:
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[17, 25, 35, 45, 100],
    labels=["18-25", "26-35", "36-45", "46+"]
)

In [60]:
df["TenureBand"] = pd.cut(
    df["YearsAtCompany"],
    bins=[-1,2,6,100],
    labels=[
        "New (0-2 Years)",
        "Mid (3-6 Years)",
        "Senior (7+ Years)"
    ]
)

In [61]:
df["IncomeBand"] = pd.qcut(
    df["MonthlyIncome"],
    q=4,
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"])

In [62]:
satisfaction_columns = [
    "EnvironmentSatisfaction",
    "JobSatisfaction",
    "RelationshipSatisfaction",
    "WorkLifeBalance"
]

df["SatisfactionScore"] = (
    df[satisfaction_columns]
    .mean(axis=1)
    .round(2)
)

In [63]:
df["PromotionStagnant"] = np.where(
    df["YearsSinceLastPromotion"] > 3,
    1,
    0
)

In [64]:
df["ManagerStabilityRatio"] = np.where(
    df["YearsAtCompany"] > 0,
    (
        df["YearsWithCurrManager"] /
        df["YearsAtCompany"]
    ).round(2),
    0
)

In [65]:
df["PromotionDelayRatio"] = np.where(
    df["YearsAtCompany"] > 0,
    (
        df["YearsSinceLastPromotion"] /
        df["YearsAtCompany"]
    ).round(2),
    0
)

In [66]:
df["IncomePerJobLevel"] = (
    df["MonthlyIncome"] /
    df["JobLevel"]
).round(2)

In [67]:
df["ExperienceBand"] = pd.cut(
    df["TotalWorkingYears"],
    bins=[-1,5,10,20,50],
    labels=[
        "0-5 Years",
        "6-10 Years",
        "11-20 Years",
        "20+ Years"
    ]
)

In [68]:
df["LongDistanceEmployee"] = np.where(
    df["DistanceFromHome"] >= 20,
    1,
    0
)

In [69]:
df["FrequentTraveller"] = np.where(
    df["BusinessTravel"] == "Travel_Frequently",
    1,
    0
)

In [70]:
df["HighSalaryHike"] = np.where(
    df["PercentSalaryHike"] >= 20,
    1,
    0
)

In [71]:
df[[
    "Attrition_Flag",
    "TenureBand",
    "AgeGroup",
    "OverTime_Flag",
    "IncomeBand",
    "SatisfactionScore",
    "PromotionStagnant",
    "ManagerStabilityRatio",
    "PromotionDelayRatio",
    "IncomePerJobLevel",
    "ExperienceBand",
    "LongDistanceEmployee",
    "FrequentTraveller",
    "HighSalaryHike"
]].head()

,Attrition_Flag,TenureBand,AgeGroup,OverTime_Flag,IncomeBand,SatisfactionScore,PromotionStagnant,ManagerStabilityRatio,PromotionDelayRatio,IncomePerJobLevel,ExperienceBand,LongDistanceEmployee,FrequentTraveller,HighSalaryHike
0,1,Mid (3-6 Years),36-45,1,High,2.00,0,0.83,0.00,2996.5,6-10 Years,0,0,0
1,0,Senior (7+ Years),46+,0,High,3.00,0,0.70,0.10,2565.0,6-10 Years,0,1,1
2,1,New (0-2 Years),36-45,1,Low,3.00,0,0.00,0.00,2090.0,6-10 Years,0,0,0
3,0,Senior (7+ Years),26-35,1,Low,3.25,0,0.00,0.38,2909.0,6-10 Years,0,1,0
4,0,New (0-2 Years),26-35,0,Medium,2.50,0,1.00,1.00,3468.0,6-10 Years,0,0,0

In [72]:
print("Final Shape:")
print(df.shape)

Final Shape:
(1470, 49)

In [73]:
print("\nFinal Columns:")
print(df.columns.tolist())

Final Columns:
['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Attrition_Flag', 'OverTime_Flag', 'AgeGroup', 'IncomeBand', 'SatisfactionScore', 'PromotionStagnant', 'ManagerStabilityRatio', 'PromotionDelayRatio', 'IncomePerJobLevel', 'ExperienceBand', 'LongDistanceEmployee', 'FrequentTraveller', 'HighSalaryHike', 'TenureBand']

In [74]:
print("\nFinal Missing Values:")
print(df.isnull().sum())

Final Missing Values:
Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
Attrition_Flag              0
OverTime_Flag               0
AgeGroup                    0
IncomeBand                  0
SatisfactionScore           0
PromotionStagnant           0
ManagerStabilityRatio       0
PromotionDelayRatio         0
IncomePerJobLevel           0
ExperienceBand              0
LongDistanceEmployee        0
FrequentTraveller           0
HighSalaryHike              0
TenureBand                  0
dtype: int64

In [75]:
print("\nAttrition Rate:")
print(round(df["Attrition_Flag"].mean()*100,2),"%")

Attrition Rate:
16.12 %

In [76]:
print("\n")
print("="*60)
print("FINAL DATASET")
print("="*60)

============================================================
FINAL DATASET
============================================================

In [77]:
df.to_csv(OUTPUT_FILE,index=False)

print("\nCleaned dataset exported successfully!")
print("Saved as:", OUTPUT_FILE)

Cleaned dataset exported successfully!
Saved as: employee_attrition_cleaned.csv